version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    platform: linux/amd64
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    networks:
        - app-network
    ports:
      - 2433:1433
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      - AZURITE_ACCOUNTS_PATH=/data/accounts
      - AZURITE_BLOB_PORT=10000
      - AZURITE_QUEUE_PORT=10001
      - AZURITE_TABLE_PORT=10002
    volumes:
      - ./.azurite:/data
  api:
    build:
      context: .
      dockerfile: ./Imagile.Api/Dockerfile
    networks:
        - app-network
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Temp1234!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./https/aspnetapp.pfx
    ports:
      - 6999:8080
      - 7000:8081
    command: ["dotnet", "Imagile.Api.dll"] #it's unclear why this is needed, as it is the same as the entrypoint
networks:
  app-network:
    driver: bridge