version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
      MSSQL_TCP_PORT: 1434
    ports:
      - 1434:1434
  api:
    build:
      context: ..
      dockerfile: ./Imagile.Api/Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Temp1234!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./https/aspnetapp.pfx
    ports:
      - 7999:8080
      - 8000:8081
    command: [ "dotnet", "Imagile.Api.dll" ] #it's unclear why this is needed, as it is the same as the entrypoint
  dev:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    depends_on:
      - api
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)networks:


