using System.Text.Json.Serialization;

namespace Imagile.Domain.Reference;

public class CountryModel(
    string name,
    string alpha2Code,
    string alpha3Code,
    string numericCode,
    string phoneDialingCode)
{
    public const string CountryCodeOfUnitedStates = "US";

    private static List<CountryModel>? _all = null;

    public string Name { get; set; } = name;
    public string CountryCodeId => Alpha2Code;

    [JsonIgnore]
    public bool IsUnitedStates => string.Equals(CountryCodeId, CountryCodeOfUnitedStates,
        StringComparison.InvariantCultureIgnoreCase);

    public string Alpha2Code { get; set; } = alpha2Code;
    public string Alpha3Code { get; set; } = alpha3Code;
    public string NumericCode { get; set; } = numericCode;
    public string PhoneDialingCode { get; set; } = phoneDialingCode;

    public static List<CountryModel> All
    {
        get
        {
            return _all ??=
            [
                new("United States of America ", "US", "USA", "840", "1"),
                new("Canada", "CA", "CAN", "124", "1"),
                new("Afghanistan", "AF", "AFG", "004", "93"),
                new("Åland Islands", "AX", "ALA", "248", "358"),
                new("Albania", "AL", "ALB", "008", "355"),
                new("Algeria", "DZ", "DZA", "012", "213"),
                new("American Samoa", "AS", "ASM", "016", "1"),
                new("Andorra", "AD", "AND", "020", "376"),
                new("Angola", "AO", "AGO", "024", "244"),
                new("Anguilla", "AI", "AIA", "660", "1"),
                new("Antarctica", "AQ", "ATA", "010", "672"),
                new("Antigua and Barbuda", "AG", "ATG", "028", "1"),
                new("Argentina", "AR", "ARG", "032", "54"),
                new("Armenia", "AM", "ARM", "051", "374"),
                new("Aruba", "AW", "ABW", "533", "297"),
                new("Australia", "AU", "AUS", "036", "61"),
                new("Austria", "AT", "AUT", "040", "43"),
                new("Azerbaijan", "AZ", "AZE", "031", "994"),
                new("Bahamas", "BS", "BHS", "044", "1"),
                new("Bahrain", "BH", "BHR", "048", "973"),
                new("Bangladesh", "BD", "BGD", "050", "880"),
                new("Barbados", "BB", "BRB", "052", "1"),
                new("Belarus", "BY", "BLR", "112", "375"),
                new("Belgium", "BE", "BEL", "056", "32"),
                new("Belize", "BZ", "BLZ", "084", "501"),
                new("Benin", "BJ", "BEN", "204", "229"),
                new("Bermuda", "BM", "BMU", "060", "1"),
                new("Bhutan", "BT", "BTN", "064", "975"),
                new("Bolivia", "BO", "BOL", "068", "591"),
                new("Bonaire, Sint Eustatius and Saba", "BQ", "BES", "535", "599"),
                new("Bosnia and Herzegovina", "BA", "BIH", "070", "387"),
                new("Botswana", "BW", "BWA", "072", "267"),
                new("Bouvet Island", "BV", "BVT", "074", "47"),
                new("Brazil", "BR", "BRA", "076", "55"),
                new("British Indian Ocean Territory ", "IO", "IOT", "086", "246"),
                new("British Virgin Islands", "VG", "VGB", "092", "1"),
                new("Brunei Darussalam", "BN", "BRN", "096", "673"),
                new("Bulgaria", "BG", "BGR", "100", "359"),
                new("Burkina Faso", "BF", "BFA", "854", "226"),
                new("Burundi", "BI", "BDI", "108", "257"),
                new("Cabo Verde", "CV", "CPV", "132", "238"),
                new("Cambodia", "KH", "KHM", "116", "855"),
                new("Cameroon", "CM", "CMR", "120", "237"),
                new("Cayman Islands ", "KY", "CYM", "136", "1"),
                new("Central African Republic", "CF", "CAF", "140", "236"),
                new("Chad", "TD", "TCD", "148", "235"),
                new("Chile", "CL", "CHL", "152", "56"),
                new("China", "CN", "CHN", "156", "86"),
                new("Christmas Island", "CX", "CXR", "162", "61"),
                new("Cocos Islands", "CC", "CCK", "166", "61"),
                new("Colombia", "CO", "COL", "170", "57"),
                new("Comoros ", "KM", "COM", "174", "269"),
                new("Congo", "CD", "COD", "180", "243"),
                new("Congo ", "CG", "COG", "178", "242"),
                new("Cook Islands ", "CK", "COK", "184", "682"),
                new("Costa Rica", "CR", "CRI", "188", "506"),
                new("Côte d'Ivoire", "CI", "CIV", "384", "225"),
                new("Croatia", "HR", "HRV", "191", "385"),
                new("Cuba", "CU", "CUB", "192", "53"),
                new("Curaçao", "CW", "CUW", "531", "599"),
                new("Cyprus", "CY", "CYP", "196", "357"),
                new("Czechia", "CZ", "CZE", "203", "420"),
                new("Denmark", "DK", "DNK", "208", "45"),
                new("Djibouti", "DJ", "DJI", "262", "253"),
                new("Dominica", "DM", "DMA", "212", "1"),
                new("Dominican Republic ", "DO", "DOM", "214", "1"),
                new("Ecuador", "EC", "ECU", "218", "593"),
                new("Egypt", "EG", "EGY", "818", "20"),
                new("El Salvador", "SV", "SLV", "222", "503"),
                new("Equatorial Guinea", "GQ", "GNQ", "226", "240"),
                new("Eritrea", "ER", "ERI", "232", "291"),
                new("Estonia", "EE", "EST", "233", "372"),
                new("Eswatini", "SZ", "SWZ", "748", "268"),
                new("Ethiopia", "ET", "ETH", "231", "251"),
                new("Falkland Islands", "FK", "FLK", "238", "500"),
                new("Faroe Islands ", "FO", "FRO", "234", "298"),
                new("Fiji", "FJ", "FJI", "242", "679"),
                new("Finland", "FI", "FIN", "246", "358"),
                new("France", "FR", "FRA", "250", "33"),
                new("French Guiana", "GF", "GUF", "254", "594"),
                new("French Polynesia", "PF", "PYF", "258", "689"),
                new("French Southern Territories ", "TF", "ATF", "260", "262"),
                new("Gabon", "GA", "GAB", "266", "241"),
                new("Gambia ", "GM", "GMB", "270", "220"),
                new("Georgia", "GE", "GEO", "268", "995"),
                new("Germany", "DE", "DEU", "276", "49"),
                new("Ghana", "GH", "GHA", "288", "233"),
                new("Gibraltar", "GI", "GIB", "292", "350"),
                new("Greece", "GR", "GRC", "300", "30"),
                new("Greenland", "GL", "GRL", "304", "299"),
                new("Grenada", "GD", "GRD", "308", "1"),
                new("Guadeloupe", "GP", "GLP", "312", "590"),
                new("Guam", "GU", "GUM", "316", "1"),
                new("Guatemala", "GT", "GTM", "320", "502"),
                new("Guernsey", "GG", "GGY", "831", "44"),
                new("Guinea", "GN", "GIN", "324", "224"),
                new("Guinea-Bissau", "GW", "GNB", "624", "245"),
                new("Guyana", "GY", "GUY", "328", "592"),
                new("Haiti", "HT", "HTI", "332", "509"),
                new("Heard Island and McDonald Islands", "HM", "HMD", "334", "672"),
                new("Holy See ", "VA", "VAT", "336", "39-06"),
                new("Honduras", "HN", "HND", "340", "504"),
                new("Hong Kong", "HK", "HKG", "344", "852"),
                new("Hungary", "HU", "HUN", "348", "36"),
                new("Iceland", "IS", "ISL", "352", "354"),
                new("India", "IN", "IND", "356", "91"),
                new("Indonesia", "ID", "IDN", "360", "62"),
                new("Iran", "IR", "IRN", "364", "98"),
                new("Iraq", "IQ", "IRQ", "368", "964"),
                new("Ireland", "IE", "IRL", "372", "353"),
                new("Isle of Man", "IM", "IMN", "833", "44"),
                new("Israel", "IL", "ISR", "376", "972"),
                new("Italy", "IT", "ITA", "380", "39"),
                new("Jamaica", "JM", "JAM", "388", "1"),
                new("Japan", "JP", "JPN", "392", "81"),
                new("Jersey", "JE", "JEY", "832", "44"),
                new("Jordan", "JO", "JOR", "400", "962"),
                new("Kazakhstan", "KZ", "KAZ", "398", "7"),
                new("Kenya", "KE", "KEN", "404", "254"),
                new("Kiribati", "KI", "KIR", "296", "686"),
                new("Korea (the Democratic People's Republic of)", "KP", "PRK", "408", "850"),
                new("Korea (the Republic of)", "KR", "KOR", "410", "82"),
                new("Kuwait", "KW", "KWT", "414", "965"),
                new("Kyrgyzstan", "KG", "KGZ", "417", "996"),
                new("Lao People's Democratic Republic ", "LA", "LAO", "418", "856"),
                new("Latvia", "LV", "LVA", "428", "371"),
                new("Lebanon", "LB", "LBN", "422", "961"),
                new("Lesotho", "LS", "LSO", "426", "266"),
                new("Liberia", "LR", "LBR", "430", "231"),
                new("Libya", "LY", "LBY", "434", "218"),
                new("Liechtenstein", "LI", "LIE", "438", "423"),
                new("Lithuania", "LT", "LTU", "440", "370"),
                new("Luxembourg", "LU", "LUX", "442", "352"),
                new("Macao", "MO", "MAC", "446", "853"),
                new("Madagascar", "MG", "MDG", "450", "261"),
                new("Malawi", "MW", "MWI", "454", "265"),
                new("Malaysia", "MY", "MYS", "458", "60"),
                new("Maldives", "MV", "MDV", "462", "960"),
                new("Mali", "ML", "MLI", "466", "223"),
                new("Malta", "MT", "MLT", "470", "356"),
                new("Marshall Islands ", "MH", "MHL", "584", "692"),
                new("Martinique", "MQ", "MTQ", "474", "596"),
                new("Mauritania", "MR", "MRT", "478", "222"),
                new("Mauritius", "MU", "MUS", "480", "230"),
                new("Mayotte", "YT", "MYT", "175", "262"),
                new("Mexico", "MX", "MEX", "484", "52"),
                new("Micronesia", "FM", "FSM", "583", "691"),
                new("Moldova", "MD", "MDA", "498", "373"),
                new("Monaco", "MC", "MCO", "492", "377"),
                new("Mongolia", "MN", "MNG", "496", "976"),
                new("Montenegro", "ME", "MNE", "499", "382"),
                new("Montserrat", "MS", "MSR", "500", "1"),
                new("Morocco", "MA", "MAR", "504", "212"),
                new("Mozambique", "MZ", "MOZ", "508", "258"),
                new("Myanmar", "MM", "MMR", "104", "95"),
                new("Namibia", "NA", "NAM", "516", "264"),
                new("Nauru", "NR", "NRU", "520", "674"),
                new("Nepal", "NP", "NPL", "524", "977"),
                new("Netherlands ", "NL", "NLD", "528", "31"),
                new("New Caledonia", "NC", "NCL", "540", "687"),
                new("New Zealand", "NZ", "NZL", "554", "64"),
                new("Nicaragua", "NI", "NIC", "558", "505"),
                new("Niger ", "NE", "NER", "562", "227"),
                new("Nigeria", "NG", "NGA", "566", "234"),
                new("Niue", "NU", "NIU", "570", "683"),
                new("Norfolk Island", "NF", "NFK", "574", "672"),
                new("North Macedonia", "MK", "MKD", "807", "389"),
                new("Northern Mariana Islands ", "MP", "MNP", "580", "1"),
                new("Norway", "NO", "NOR", "578", "47"),
                new("Oman", "OM", "OMN", "512", "968"),
                new("Pakistan", "PK", "PAK", "586", "92"),
                new("Palau", "PW", "PLW", "585", "680"),
                new("Palestine, State of", "PS", "PSE", "275", "970"),
                new("Panama", "PA", "PAN", "591", "507"),
                new("Papua New Guinea", "PG", "PNG", "598", "675"),
                new("Paraguay", "PY", "PRY", "600", "595"),
                new("Peru", "PE", "PER", "604", "51"),
                new("Philippines ", "PH", "PHL", "608", "63"),
                new("Pitcairn", "PN", "PCN", "612", "870"),
                new("Poland", "PL", "POL", "616", "48"),
                new("Portugal", "PT", "PRT", "620", "351"),
                new("Puerto Rico", "PR", "PRI", "630", "1"),
                new("Qatar", "QA", "QAT", "634", "974"),
                new("Réunion", "RE", "REU", "638", "262"),
                new("Romania", "RO", "ROU", "642", "40"),
                new("Russian Federation ", "RU", "RUS", "643", "7"),
                new("Rwanda", "RW", "RWA", "646", "250"),
                new("Saint Barthélemy", "BL", "BLM", "652", "590"),
                new("Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", "654", "290"),
                new("Saint Kitts and Nevis", "KN", "KNA", "659", "1"),
                new("Saint Lucia", "LC", "LCA", "662", "1"),
                new("Saint Martin", "MF", "MAF", "663", "590"),
                new("Saint Pierre and Miquelon", "PM", "SPM", "666", "508"),
                new("Saint Vincent and the Grenadines", "VC", "VCT", "670", "1"),
                new("Samoa", "WS", "WSM", "882", "685"),
                new("San Marino", "SM", "SMR", "674", "378"),
                new("Sao Tome and Principe", "ST", "STP", "678", "239"),
                new("Saudi Arabia", "SA", "SAU", "682", "966"),
                new("Senegal", "SN", "SEN", "686", "221"),
                new("Serbia", "RS", "SRB", "688", "381"),
                new("Seychelles", "SC", "SYC", "690", "248"),
                new("Sierra Leone", "SL", "SLE", "694", "232"),
                new("Singapore", "SG", "SGP", "702", "65"),
                new("Sint Maarten", "SX", "SXM", "534", "1"),
                new("Slovakia", "SK", "SVK", "703", "421"),
                new("Slovenia", "SI", "SVN", "705", "386"),
                new("Solomon Islands", "SB", "SLB", "090", "677"),
                new("Somalia", "SO", "SOM", "706", "252"),
                new("South Africa", "ZA", "ZAF", "710", "27"),
                new("South Georgia", "GS", "SGS", "239", "500"),
                new("South Sudan", "SS", "SSD", "728", "211"),
                new("Spain", "ES", "ESP", "724", "34"),
                new("Sri Lanka", "LK", "LKA", "144", "94"),
                new("Sudan ", "SD", "SDN", "729", "249"),
                new("Suriname", "SR", "SUR", "740", "597"),
                new("Svalbard and Jan Mayen", "SJ", "SJM", "744", "47"),
                new("Sweden", "SE", "SWE", "752", "46"),
                new("Switzerland", "CH", "CHE", "756", "41"),
                new("Syrian Arab Republic ", "SY", "SYR", "760", "963"),
                new("Taiwan", "TW", "TWN", "158", "886"),
                new("Tajikistan", "TJ", "TJK", "762", "992"),
                new("Tanzania, the United Republic of", "TZ", "TZA", "834", "255"),
                new("Thailand", "TH", "THA", "764", "66"),
                new("Timor-Leste", "TL", "TLS", "626", "670"),
                new("Togo", "TG", "TGO", "768", "228"),
                new("Tokelau", "TK", "TKL", "772", "690"),
                new("Tonga", "TO", "TON", "776", "676"),
                new("Trinidad and Tobago", "TT", "TTO", "780", "1"),
                new("Tunisia", "TN", "TUN", "788", "216"),
                new("Turkey", "TR", "TUR", "792", "90"),
                new("Turkmenistan", "TM", "TKM", "795", "993"),
                new("Turks and Caicos Islands ", "TC", "TCA", "796", "1"),
                new("Tuvalu", "TV", "TUV", "798", "688"),
                new("Uganda", "UG", "UGA", "800", "256"),
                new("Ukraine", "UA", "UKR", "804", "380"),
                new("United Arab Emirates", "AE", "ARE", "784", "971"),
                new("United Kingdom", "GB", "GBR", "826", "44"),
                new("Uruguay", "UY", "URY", "858", "598"),
                new("US Virgin Islands", "VI", "VIR", "850", "1"),
                new("Uzbekistan", "UZ", "UZB", "860", "998"),
                new("Vanuatu", "VU", "VUT", "548", "678"),
                new("Venezuela", "VE", "VEN", "862", "58"),
                new("Viet Nam", "VN", "VNM", "704", "84"),
                new("Wallis and Futuna", "WF", "WLF", "876", "681"),
                new("Western Sahara", "EH", "ESH", "732", "212"),
                new("Yemen", "YE", "YEM", "887", "967"),
                new("Zambia", "ZM", "ZMB", "894", "260"),
                new("Zimbabwe", "ZW", "ZWE", "716", "263")
            ];
        }
    }
}