name: Publish CLI NuGet Package
on:
    push:
        branches:
        - main

jobs:
    call-workflow-passing-data:
        uses: .github/workflows/nuget.yml@main
        with:
            project-name: 'Imagile.Cli'
